name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 10
    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-executable: gradlew
        arguments: buildPlugin
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/distributions/*
